name = "EinSumToZX"
uuid = "806b846c-d1c1-499d-8507-f7c73a536ebf"
authors = ["Yusheng Zhao"]
version = "1.0.0-DEV"

[compat]
julia = "1.9.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
